---
apiVersion: v1
kind: Template
labels:
  template: projectrequest-template
message: |-
  The following project/namespace has been created: ${NAMESPACE}
metadata:
  annotations:
    description: |-
      ProjectRequest Template
  creationTimestamp: null
  name: ${NAMESPACE}
objects:
- apiVersion: ${PROJECT_REQUEST_API_VERSION}
  kind: ProjectRequest
  metadata:
    name: ${NAMESPACE}
  description: '${NAMESPACE_DESCRIPTION}' 
  displayName: '${NAMESPACE_DISPLAY_NAME}'
parameters:
- description: Name
  displayName: Name
  name: NAMESPACE
  required: true
- description: DisplayName
  displayName: DisplayName
  name: NAMESPACE_DISPLAY_NAME
  required: true
- description: Description
  displayName: Description
  name: NAMESPACE_DESCRIPTION
- description: API version for ProjectRequest
  displayName: ProjectRequest API version
  name: PROJECT_REQUEST_API_VERSION
  value: project.openshift.io/v1
  required: true
  
